### ISSUE TITLE
jre Failed .

### ISSUE THREAD

**Issue by parasuraam** [beryx-gist/badass-runtime-example-javafx#12]
when I build jpackage in ubuntu.

It comes like this

![1](https://user-images.githubusercontent.com/67687893/91195815-fa213b00-e716-11ea-9dec-b4af049b9b24.PNG)

How can I solve this ?

**Comment by Srijan-Sengupta** [comment]
I also faced the same problem. But when I changed my JDK , keeping the version same, It worked correctly. I use [Zulu JDK](https://www.azul.com/downloads/zulu-community/?architecture=x86-64-bit&package=jdk)

**Comment by parasuraam** [comment]
I tried but the same error.

**Comment by siordache** [comment]
As @Srijan-Sengupta already said, you need to install another JDK.
See this discussion: https://github.com/beryx/badass-jlink-plugin/issues/111.
See also [this](https://bugs.launchpad.net/ubuntu/+source/openjdk-14/+bug/1868699) and [this](https://github.com/AdoptOpenJDK/openjdk-build/issues/1804).
