### ISSUE TITLE
Cross-Platform Installers

### ISSUE THREAD

**Issue by Srijan-Sengupta** [beryx-gist/badass-runtime-example-javafx#13]
I have seen this example contains native Installer for almost all major platform. How this Installers were made when JPackage  is not cross platform. Please help me out to understand this.

**Comment by siordache** [comment]
The installers are created via [GitHub Actions](https://github.com/features/actions): the Gradle build is executed on each platform using [this configuration file](https://github.com/beryx-gist/badass-runtime-example-javafx/blob/master/.github/workflows/gradle.yml).

**Comment by Srijan-Sengupta** [comment]
Thank you very much. It helped me in creating installers for all platform of my project [Paint-India](https://github.com/Srijan-Sengupta/Paint-India-Gradle-Desktop) here are the [installers](https://github.com/Srijan-Sengupta/Paint-India-Gradle-Desktop/actions/runs/228579740)

**Comment by Srijan-Sengupta** [comment]
Thank you once again
