### ISSUE TITLE
When I add libs it comes an error.

### ISSUE THREAD

**Issue by parasuraam** [beryx-gist/badass-runtime-example-javafx#14]
I added these three [libs.zip](https://github.com/beryx-gist/badass-runtime-example-javafx/files/5201036/libs.zip) in my project.  But , When  I run my project it comes an  some error like 
`package  does not exist`

    16:09:21: Executing task 'Launcher.main()'...
  
    Starting Gradle Daemon...
    Gradle Daemon started in 3 s 249 ms

    > Configure project :
    Project : => no module-info.java found

    > Task :compileJava
    F:\webcam\badass-runtime-example-javafx-master\src\main\java\org\example\hellofx\WebCamPreviewController.java:26: error: 
    package com.github.sarxos.webcam does not exist
    
    import com.github.sarxos.webcam.Webcam;
                               ^
    F:\webcam\badass-runtime-example-javafx-master\src\main\java\org\example\hellofx\WebCamPreviewController.java:40: error: 
     cannot find symbol
	private Webcam selWebCam = null;
	        ^
     symbol:   class Webcam
     location: class WebCamPreviewController
    F:\webcam\badass-runtime-example-javafx-master\src\main\java\org\example\hellofx\WebCamPreviewController.java:53: error: 
    cannot find symbol
		for(Webcam webcam:Webcam.getWebcams())
		                  ^
    symbol:   variable Webcam
    location: class WebCamPreviewController
    F:\webcam\badass-runtime-example-javafx-master\src\main\java\org\example\hellofx\WebCamPreviewController.java:53: error: 
    cannot find symbol
		for(Webcam webcam:Webcam.getWebcams())
		    ^
    symbol:   class Webcam
    location: class WebCamPreviewController
    F:\webcam\badass-runtime-example-javafx-master\src\main\java\org\example\hellofx\WebCamPreviewController.java:105: 
    error: cannot find symbol
					selWebCam = Webcam.getWebcams().get(webCamIndex);
					            ^
    symbol: variable Webcam
    F:\webcam\badass-runtime-example-javafx-master\src\main\java\org\example\hellofx\WebCamPreviewController.java:110: 
    error: cannot find symbol
					selWebCam = Webcam.getWebcams().get(webCamIndex);
					            ^
    symbol: variable Webcam
    F:\webcam\badass-runtime-example-javafx-master\src\main\java\org\example\hellofx\WebCamPreviewController.java:195: 
    error: cannot find symbol
		Webcam.shutdown();
		^
    symbol:   variable Webcam
    location: class WebCamPreviewController
    7 errors

    > Task :compileJava FAILED

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':compileJava'.
    > Compilation failed; see the compiler error output for details.

    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to 
    get full insights.

    * Get more help at https://help.gradle.org
 
    BUILD FAILED in 19s
    1 actionable task: 1 executed
    16:09:50: Task execution finished 'Launcher.main()'.

My project

[badass-runtime-example-javafx-master.zip](https://github.com/beryx-gist/badass-runtime-example-javafx/files/5201081/badass-runtime-example-javafx-master.zip)

Why this error comes?

How can I solve this error?

**Comment by siordache** [comment]
You need to tell Gradle that your project depends on these libraries. Put this in your build.gradle:
```
repositories {
    mavenCentral()
    flatDir {
        dirs 'libs'
    }
}

dependencies {
    implementation name: 'bridj-0.6.3-20130316.190111-13'
    implementation name: 'slf4j-api-1.7.2'
    implementation name: 'webcam-capture-0.3.10-RC7'
}
```

**Comment by parasuraam** [comment]
@siordache Thank you!!!
