### ISSUE TITLE
How can I set the publisher name ?

### ISSUE THREAD

**Issue by parasuraam** [beryx-gist/badass-runtime-example-javafx#15]
In `Control Panel\Programs\Programs and Features` there is a publisher name.

![pubname](https://user-images.githubusercontent.com/67687893/93089562-1b8f9a00-f6b9-11ea-8908-195d33f2aefe.PNG)

How can I set the publisher name ?

**Comment by siordache** [comment]
```
jpackage {
    ...
    installerOptions += ['--vendor', 'Acme Corporation']
    ...
}
```

**Comment by parasuraam** [comment]
@siordache   Thank you!!!
