### ISSUE TITLE
Icon image of linux - JPackage Image

### ISSUE THREAD

**Issue by Srijan-Sengupta** [beryx-gist/badass-runtime-example-javafx#16]
How do i change the icon of my application from default icon of JPackage Image to another Image of mine and also how can I configure the .desktop file of the deb and rpm file?

**Comment by siordache** [comment]
For changing the icon, see [this answer](https://github.com/beryx-gist/badass-runtime-example-javafx/issues/11#issuecomment-680822632).

I didn't try it myself, but [as described here](https://docs.oracle.com/en/java/javase/14/jpackage/override-jpackage-resources.html#GUID-405708DC-0243-49FC-84D9-B2A7F0A011A9), you need to add your customized .desktop file to the resource directory. In the case of this example project, this means that you need to put a `hellofx.desktop` file into `src/main/resources`.

**Comment by Srijan-Sengupta** [comment]
I am extremely sorry to open an issue on runtime plugin when I was using jlink plugin. Very sorry for that, I am closing this Issue.
Thank you.
