### ISSUE TITLE
How to create a jpackage for windows 32 bit ?

### ISSUE THREAD

**Issue by poorvajappja** [beryx-gist/badass-runtime-example-javafx#18]
I am using windows 64 bit. I successfully created a Jpackage with java JDK 14 with 64 bit.

I have only one laptop.

I want to create  a Jpackage for windows 32 bit.

How can I do this ?

**Comment by siordache** [comment]
I usually use GitHub Actions (as in [this example](https://github.com/beryx-gist/badass-runtime-example-javafx/blob/master/.github/workflows/gradle.yml)) to create [packages for different platforms](https://github.com/beryx-gist/badass-runtime-example-javafx/actions/runs/225251734). Another option is to use one of the CI tools supported by GitHub (such as Travis, AppVeyor, or CircleCI). 

However, none of the above mentioned tools has support for Windows 32-bit.

I didn't try it myself, but I think [Azure Pipelines](https://github.com/marketplace/azure-pipelines) is the tool you need for your use case. See [this project](https://github.com/brunoborges/javafx-jlink-starter-gradle) for an example.
To configure a Windows 32-bit architecture you probably need to add `arch: ia32` to [the list of parameters](https://github.com/brunoborges/javafx-jlink-starter-gradle/blob/410b15b4e2ed0aa6ac835abfc498a7d9ce22d6da/azure-pipelines.yml#L32-L35) for your job.

**Comment by parasuraam** [comment]
I did'nt  know about yaml.

I want to create an installer for 32 bit.

But , where can I add this `arch: ia32` .


     name: Gradle Build

    on: [push, pull_request]

    jobs:
    build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        java: [ '15.0.1' ]
      fail-fast: false
    name: ${{ matrix.os }}
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Echo JAVA_HOME
      run: echo $JAVA_HOME
    - name: Verify Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Execute build
      run: ./gradlew --info --stacktrace build
    - name: Execute runtime
      run: ./gradlew --info --stacktrace runtime
    - name: Execute jpackage
      run: ./gradlew --info --stacktrace jpackage
    - name: Upload DMG as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: hellofx-jdk${{ matrix.java }}-${{ matrix.os }}-dmg
        path: build/jpackage/*.dmg
    - name: Upload EXE as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: hellofx-jdk${{ matrix.java }}-${{ matrix.os }}-exe
        path: build/jpackage/*.exe
    - name: Upload MSI as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: hellofx-jdk${{ matrix.java }}-${{ matrix.os }}-msi
        path: build/jpackage/*.msi
    - name: Upload DEB as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: hellofx-jdk${{ matrix.java }}-${{ matrix.os }}-deb
        path: build/jpackage/*.deb
    - name: Upload RPM as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: hellofx-jdk${{ matrix.java }}-${{ matrix.os }}-rpm
        path: build/jpackage/*.rpm


Give a solution for this ?
