### ISSUE TITLE
runtime won't produce any JRE

### ISSUE THREAD

**Issue by jscancella** [beryx-gist/badass-runtime-example-javafx#19]
When I run `.\gradlew.bat runtime` and I try and run `build\install\SuperDeDuper\bin\SuperDeDuper.bat` it errors saying that there isn't a proper JRE installed. Isn't `.\gradlew.bat runtime` supposed to generate a JRE for the application?

Here is a link to my build file: https://github.com/jscancella/deduplicator/blob/8fce42a1b8af7ac69735cf796a652a7d0266e242/build.gradle based on the example JavaFX you have.

**Comment by jscancella** [comment]
After changing to use `java.exe` instead of `javaw.exe` I see the error 
> Error: JavaFX runtime components are missing, and are required to run this application

Why are they not being detected when they are present in `build\image\lib`?

**Comment by Srijan-Sengupta** [comment]
See [this](http://mail.openjdk.java.net/pipermail/openjfx-dev/2018-June/021980.html) please.

**Comment by siordache** [comment]
@jscancella  You should use `build\image\bin\SuperDeDuper.bat` instead of `build\install\SuperDeDuper\bin\SuperDeDuper.bat`.

**Comment by kaushalyap** [comment]
@siordache when I execute one in the image it says 

`Error: JavaFX runtime components are missing, and are required to run this application`

Any way to fix this?

**Comment by siordache** [comment]
Do you have a [Launcher](https://github.com/beryx-gist/badass-runtime-example-javafx/blob/master/src/main/java/org/example/hellofx/Launcher.java) class for your application?

**Comment by kaushalyap** [comment]
@siordache thanks for quick reply, it was not there, but I add it as follows, since I am using Kotlin

```
package example.app

object Launcher {
    @JvmStatic
    fun main(args: Array<String>) {
        App.main(args)
    }
}
```
still getting the same error.

**Comment by siordache** [comment]
Did you also update the `mainClass` in build.gradle.kts?
```
application {
    mainClass = 'example.app.LauncherKt'
}
```

**Comment by kaushalyap** [comment]
@siordache thanks a lot it does work now.  there should not be a Kt postfix at the end though.
