### ISSUE TITLE
How to create a jpackage for mac os without mac machine?

### ISSUE THREAD

**Issue by parasuraam** [beryx-gist/badass-runtime-example-javafx#23]
I created jpackage successfully for windows and linux os.

I want to create  a jpackage for mac os.

But , I have only one  windows machine. 

I want to create a jpackage for mac os without mac machine. 

My friend says 

![20201016_100607](https://user-images.githubusercontent.com/70012957/96214068-2bd8b480-0f98-11eb-9644-2a9c963f947f.jpg)

Is it possible to create a jpackage for mac os without mac machine ?

**Comment by siordache** [comment]
I don't have experience with NetBeans, but this project uses [GitHub Actions](https://github.com/features/actions) to create [package installers for different platforms](https://github.com/beryx-gist/badass-runtime-example-javafx/actions/runs/277195113), including macOS. GitHub Actions gives you free access to virtual machines running Windows, Linux and macOS, so you don't need to own a Mac to create a package for macOS. [This configuration file](https://github.com/beryx-gist/badass-runtime-example-javafx/blob/master/.github/workflows/gradle.yml) instructs GitHub to execute the Gradle build on each of the three platforms.
