### ISSUE TITLE
when I open exe and msi files it comes "windows protected your pc".

### ISSUE THREAD

**Issue by parasuraam** [beryx-gist/badass-runtime-example-javafx#24]
when I open exe and msi files it comes "windows protected your pc".

![win](https://user-images.githubusercontent.com/67687893/97769395-67d85180-1b22-11eb-9ae2-cd93d1b2a3dc.PNG)

How can I solve this ?

**Comment by siordache** [comment]
Click on "More info" and then "Run anyway".

**Comment by parasuraam** [comment]
But , why this comes like https://user-images.githubusercontent.com/67687893/97769395-67d85180-1b22-11eb-9ae2-cd93d1b2a3dc.PNG

I want to remove this.

How can I do this?

**Comment by siordache** [comment]
This warning is displayed by [Microsoft Defender SmartScreen](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-overview).
You can disable SmartScreen on your machine, but the warning will still appear on other machines that have SmartScreen enabled.

To get rid of this warning on any machine, you need to sign your exe or msi installer with an [Extended Validation code signing certificate](https://docs.microsoft.com/en-us/archive/blogs/ie/microsoft-smartscreen-extended-validation-ev-code-signing-certificates). However, these certificates are not cheap (see [here](https://en.sklep.certum.pl/data-safety/code-signing-certificates/certum-ev-code-sigining.html) for example).

**Comment by parasuraam** [comment]
@siordache thanks for reply!!!!
