### ISSUE TITLE
dpkg : error processing package.

### ISSUE THREAD

**Issue by parasuraam** [beryx-gist/badass-runtime-example-javafx#26]
dpkg : error processing  package .

I build jpackage with ubuntu. 
It works smoothly on ubuntu. 

But , when I install my deb file on kali linux it comes an error.

![IMG-20201107-WA0019](https://user-images.githubusercontent.com/67687893/98428658-7a293100-20c8-11eb-8480-48c6c00602f6.jpg)

How can I solve this error?

**Comment by parasuraam** [comment]
![IMG-20201107-WA0020](https://user-images.githubusercontent.com/67687893/98429224-63d0a480-20cb-11eb-831f-fc7f828aa7cb.jpg)

When I install xdg-utils it comes like this.

**Comment by Srijan-Sengupta** [comment]
@parasuraam , you must try `sudo apt install xdg-utils` if it does not work, then you must : 
1. install synaptic `sudo apt install synaptic`
2. open `Synaptic Package Manager`
3. on the top left corner you will find search button and you will have to click on it.
4.  next search for `xdg-utils` next at last you will find it.
5. click on the check box just left to the text and then on the pop-up click `Mark for Installation`
6. finally, click on `Apply` button just in the above menu bar.
this will install xdg-utils and again you have to run the installation.

if these two methods don't work, please try `sudo apt install /path/to/the/package` please replace `/path/to/the/package` with the path to the debian file with its fully classified or relative path

**Comment by parasuraam** [comment]
![IMG-20201107-WA0046](https://user-images.githubusercontent.com/67687893/98453267-52e06b80-217d-11eb-8321-374954977200.jpg)

When I install synaptic it comes like this.

**Comment by Srijan-Sengupta** [comment]
Please give me your system's full details including the environment.
Did you ran sudo apt install path/to/package? Where path/to/package is the
absolute or relative path to the package you want to install?

**Comment by Srijan-Sengupta** [comment]
Hey @parasuraam Try running the command and give the output here.
`grep -v '#' /etc/apt/sources.list | sort -u`

**Comment by parasuraam** [comment]
![IMG-20201128-WA0005](https://user-images.githubusercontent.com/67687893/100496974-709e6080-317e-11eb-8942-9d4b1ca615a6.jpg)

It comes like this.

**Comment by Srijan-Sengupta** [comment]
Yea! Here the problem lies!
You have no repository added to the file, `sources.list`.
So, you need to run, 
`echo "deb http://http.kali.org/kali kali-rolling main non-free contrib" | sudo tee /etc/apt/sources.list`
then,`sudo apt update && sudo apt upgrade`
You are also recommended to restart the computer or virtualbox..
And then, follow these instructions:
https://github.com/beryx-gist/badass-runtime-example-javafx/issues/26#issuecomment-723427973

For further information, see: https://www.kali.org/docs/general-use/kali-linux-sources-list-repositories/

**Comment by parasuraam** [comment]
1. `echo "deb http://http.kali.org/kali kali-rolling main non-free contrib" | sudo tee /etc/apt/sources.list`

![cm1](https://user-images.githubusercontent.com/67687893/100533334-08419480-31fb-11eb-903d-5850538fd9e0.jpg)

2. `sudo apt update && sudo apt upgrade`

![cm2](https://user-images.githubusercontent.com/67687893/100533345-463eb880-31fb-11eb-8072-c0437a145d2f.jpg)

after this completed.

I runned this .

1. `sudo apt install xdg-utils`

![cm3](https://user-images.githubusercontent.com/67687893/100533387-99b10680-31fb-11eb-9cf8-1c4ca3d19d39.jpg)

2. `sudo apt install synaptic`

![cm4](https://user-images.githubusercontent.com/67687893/100533402-c7964b00-31fb-11eb-9b00-5de36ee14df7.jpg)

**Comment by Srijan-Sengupta** [comment]
You must try this: 
- `echo -e "deb http://http.kali.org/kali sana main non-free contrib\ndeb http://security.kali.org/kali-security/ sana/updates main contrib non-free" > /etc/apt/sources.list` 

- and then `sudo apt upgrade && sudo apt update`

 - and finally, `sudo apt install /path/to/the/package` **remember to replace `/path/to/the/package` with the absolute or relative path loaction.**

**Comment by parasuraam** [comment]
How can I find absolute path ???
