### ISSUE TITLE
Could not resolve all files for configuration ':compileClasspath'.

### ISSUE THREAD

**Issue by parasuraam** [beryx-gist/badass-runtime-example-javafx#31]
Build.gradle

          dependencies {
                          
              compile group: 'org.jetbrains.pty4j', name: 'pty4j', version: '0.9.8'

               }

When I add pty4j lib . It comes like this,

     03:42:25: Executing task 'Launcher.main()'...

     > Configure project :
     Project : => no module-info.java found
 
     > Task :compileJava FAILED

     Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
     Use '--warning-mode all' to show the individual deprecation warnings.
     See https://docs.gradle.org/6.5.1/userguide/command_line_interface.html#sec:command_line_warnings
     1 actionable task: 1 executed

     FAILURE: Build failed with an exception.

     * What went wrong:
     Execution failed for task ':compileJava'.
     > Could not resolve all files for configuration ':compileClasspath'.
      > Could not find org.jetbrains.pty4j:pty4j:0.9.8.
      Searched in the following locations:
        - https://repo.maven.apache.org/maven2/org/jetbrains/pty4j/pty4j/0.9.8/pty4j-0.9.8.pom
        - file:/C:/Users/parasu/Documents/badass-runtime-example-javafx-master/libs/pty4j-0.9.8.jar
        - file:/C:/Users/parasu/Documents/badass-runtime-example-javafx-master/libs/pty4j.jar
      Required by:
          project :

     * Try:
     Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

     * Get more help at https://help.gradle.org
 
     BUILD FAILED in 1s
     03:42:27: Task execution finished 'Launcher.main()'.

How can I solve this ?

**Comment by Srijan-Sengupta** [comment]
Hey @parasuraam , have you added, 
```
repositories {
  maven {
    url  "https://jetbrains.bintray.com/pty4j"
  }
}
```
in the build.gradle?

**Comment by Srijan-Sengupta** [comment]
If not, please add.

**Comment by parasuraam** [comment]
@Srijan-Sengupta It worked . thank you very much!!!
