### ISSUE TITLE
Give an example for jni projects.

### ISSUE THREAD

**Issue by poorvajappja** [beryx-gist/badass-runtime-example-javafx#36]
How ro create a jpackage with jni projects with github action ?

I have many doubts.

So , please give a sample jni project.

**Comment by poorvajappja** [comment]
Java native interface (jni) allows calling native libraries 

Windows  --> .dell
Linux         --> .so
Mac           -->.deliberately

I didn't know more about jni.

So , give an example project.

**Comment by stanlygamer** [comment]
give an example project for cmake.
 because, cmake is more easier to build jni apps with gradle for all platforms like windows , linux and mac.
