### ISSUE TITLE
How to add The Badass Runtime Plugin in maven project ?

### ISSUE THREAD

**Issue by poorvajappja** [beryx-gist/badass-runtime-example-javafx#9]
How to add The Badass Runtime Plugin in maven project ?

For gradle I added The Badass Runtime Plugin like this and it worked.

    plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.0.8'
    id 'org.beryx.runtime' version '1.8.1'
    }

    repositories {
    mavenCentral()
    }

    javafx {
    modules = ['javafx.controls']
    }

    application {
    mainClassName = "org.example.hellofx.Launcher"
    applicationName = 'hellofx'
    }

    runtime {
    options = ['--strip-debug', '--compress', '2', '--no-header-files', '--no-man-pages']
    jpackage {
        // jpackageHome = '/usr/lib/jvm/jdk14'
        if(org.gradle.internal.os.OperatingSystem.current().windows) {
            installerType = 'msi'
            // imageOptions = ['--win-console']
            installerOptions = ['--win-per-user-install', '--win-dir-chooser', '--win-menu', '--win-shortcut']
        }
    }
    }

How can I add the BADASS Runtime Plugin  in  maven project ?

When I add BADASS Runtime Plugin  dependency it comes an error.

    
    <dependency>
    <groupId>gradle.plugin.org.beryx</groupId>
    <artifactId>badass-runtime-plugin</artifactId>
    <version>1.8.0</version>
    </dependency>

After adding this . It comes `Cannot resolve gradle.plugin.org.beryx:badass-runtime-plugin:1.8.0`

Can you give a sample pom.xml file for The Badass Runtime Plugin?

**Comment by siordache** [comment]
This plugin is only for Gradle. You cannot use it with Maven.

**Comment by poorvajappja** [comment]
Ok , thanks for reply.

**Comment by poorvajappja** [comment]
The badass-runtime-plugin is only for Gradle. But , I am using maven. was there any plugin for maven like badass-runtime-plugin?

**Comment by siordache** [comment]
You may have a look at https://github.com/moditect/moditect.

**Comment by poorvajappja** [comment]
I am using slf4j with javafx project.  Can you give more information?
Because,  I did not understand  https://github.com/beryx-gist/badass-runtime-example-javafx/issues/9#issuecomment-658597996

**Comment by siordache** [comment]
ModiTect is a Maven plugin that lets you create custom runtime images, but I don't know if it is the best tool for your use case. The following Maven plugins may also be interesting for you (but I didn't try them yet):
- https://tentackle.org/static-content/sitedocs/tentackle/latest/tentackle-jlink-maven-plugin/jlink-mojo.html
- https://maven.apache.org/plugins/maven-jlink-plugin/

**Comment by poorvajappja** [comment]
Thanks for reply.
